apiVersion: v2
name: blockchain-node
description: A Helm chart to deploy a blockchain node

type: application

version: 0.1.8
# Not compatible with 0.0.1 due to change container.command

appVersion: "1.17.0"

maintainers:
  - name: pokt-foundation
  - name: vlad
  - name: HebertCL
