statefulset: []

additionalManifests: []

global:
  chainHealthcheckSidecar:
    repository: eepokt/chain-healthcheck-sidecar
    tag: master
  serviceAccount:
    create: true
    # name: "pokt"
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
    fsGroupChangePolicy: "OnRootMismatch"
