global:
  imagePullPolicy: Always
  syncLatestVolumeSnapshot:
    enable: true
    latestVolumeSnapshotNamespace: pokt-latest
    latestVolumeSnapshotName: backups
  chainHealthcheckSidecar:
    repository: eepokt/chain-healthcheck-sidecar
    tag: master
  serviceAccount:
    create: true
    name: change-me
    # annotations: []
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
    fsGroupChangePolicy: "OnRootMismatch"
statefulset: []

additionalManifests: []
