{{- if $.Values.externalSecrets.create }}
{{ range $v := $.Values.iamPolicy.secretRoles }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "sec-%s-%s" $v.secret $v.project | trunc 63 | trimSuffix "-" }}
spec:
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "sec-%s" $v.project | trunc 63 | trimSuffix "-" }}
  target:
    name: {{ $v.secret }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ $v.secret }}
---
{{- end }}
{{- end }}
