{{ range $.Values.iamPolicyMember.secretIDs }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-{{ . | lower | replace "_" "-" | trunc 63 | trimSuffix "-"}}
spec:
  member: "serviceAccount:{{ $.Values.iamPolicyMember.iamMember }}@{{ required "Desired Project ID is required" $.Values.iamPolicyMember.clusterProjectID }}.iam.gserviceaccount.com"
  role: "roles/secretmanager.secretAccessor"
  resourceRef:
    apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: "projects/{{ required "Desired Project ID is required"  $.Values.iamPolicyMember.secretProjectID }}/secrets/{{ . }}"
{{ end }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-service-account
spec:
  member: "serviceAccount:{{ $.Values.iamPolicyMember.workloadIdentityEndpoint }}[{{$.Values.iamPolicyMember.namespace}}/{{ $.Values.iamPolicyMember.iamMember }}]"
  role: "roles/iam.serviceAccountTokenCreator"
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ $.Values.iamPolicyMember.iamMember }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-workload-identity
spec:
  member: "serviceAccount:{{ $.Values.iamPolicyMember.iamMember }}@{{ required "Desired Project ID is required" $.Values.iamPolicyMember.clusterProjectID }}.iam.gserviceaccount.com"
  role: "roles/iam.workloadIdentityUser"
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ $.Values.iamPolicyMember.iamMember }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $.Values.iamPolicyMember.iamMember }}
  annotations:
    cnrm.cloud.google.com/project-id: "{{ required "Desired Project ID is required"  $.Values.iamPolicyMember.clusterProjectID }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.iamPolicyMember.iamMember }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ $.Values.iamPolicyMember.iamMember }}@{{ required "Desired Project ID is required" $.Values.iamPolicyMember.clusterProjectID }}.iam.gserviceaccount.com"
