apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.iamPolicy.gke.serviceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ $.Values.iamPolicy.gke.serviceAccount }}@{{ $.Values.iamPolicy.gke.clusterProjectID }}.iam.gserviceaccount.com"
