{{- if .Values.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "pokt-portal-ui-backend.fullname" . }}
    chart: {{ template "pokt-portal-ui-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end }}
