{{- if .Values.externalSecrets.enabled -}}

kind: SecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: {{ include "pokt-portal-v2.fullname" . }}-ss
spec:
  controller: ""
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpsm.ProjectID }}
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: {{ .Values.externalSecrets.gcpsm.clusterLocation }}
          # name of the GKE cluster
          clusterName: {{ .Values.externalSecrets.gcpsm.clusterName }}
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: {{ .Values.externalSecrets.gcpsm.ProjectID }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.gcpsm.serviceAccount.name }}
            namespace: {{ .Values.externalSecrets.gcpsm.serviceAccount.namespace }}
{{- end -}}
