repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/pokt-foundation/charts
  rev: v0.1.0
  hooks:
    - id: helm-docs
      args: []
