{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: release-watch
spec:
  controller: ""
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: k8s-tooling-us-east-1
          role: release-watch
          serviceAccountRef:
            name: release-watch
      namespace: admin/engineering/
      path: /devops/release-watch
      server: https://hcp-vault-cluster-a-public-vault-72230702.bb94b393.z1.hashicorp.cloud:8200
      version: v1
  refreshInterval: 0
{{ end -}}
