apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokt-middleware.fullname" . }}
  labels:
    {{- include "pokt-middleware.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pokt-middleware.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pokt-middleware.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pokt-middleware.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probes.enabled }}
          {{ include "pokt-middleware.probes" . | nindent 10 }}
          {{- end }}
          env:
          {{- with .Values.env }}
          {{- toYaml . | nindent 12}}
          {{- end }}
          - name: CONFIG_FILE
            value: {{ printf "%s/%s" ( trimSuffix "/" .Values.configMountPath ) "config.json"}}
          - name: PORT
            value: "{{ .Values.service.port | default 80 }}"
          {{- if .Values.envFromSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.envFromSecret }}
          {{- end }}
          volumeMounts:
          - mountPath: {{ .Values.configMountPath }}
            readOnly: true
            name: portal-middleware-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: portal-middleware-config
          secret:
            secretName: {{ .Values.secretName | quote }}
            items:
              - key: "config.json"
                path: "config.json"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
