apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "polygon-edge.fullname" . }}
  labels:
    {{- include "polygon-edge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "polygon-edge.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "polygon-edge.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "polygon-edge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "polygon-edge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - polygon-edge
          args:
            - server
            - --data-dir
            - /root/polygon-edge-datadir
            - --chain
            - /root/polygon-edge-datadir/genesis.json
            - --libp2p
            - 0.0.0.0:1478
            - --seal
            # Extra/un-managed arguments
            {{- range .Values.polygonEdge.extraArgs }}
            {{- if .name }}
            - {{ printf "--%s" .name }}
            {{- end }}
            {{- if .value }}
            - "{{ .value }}"
            {{- end }}
            {{- end }}
          ports:
            - name: p2p
              containerPort: {{ .Values.p2p.port }}
              protocol: TCP
            - name: jsonrpc
              containerPort: {{ .Values.jsonrpc.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.jsonrpc.port }}
            initialDelaySeconds: 25
            periodSeconds: 10
          volumeMounts:
            - name: polygon-edge-datadir
              mountPath: /root/polygon-edge-datadir
            - name: validator-config
              mountPath: /root/polygon-edge-datadir/consensus/validator.key
              subPath: validator.key
            - name: validator-config
              mountPath: /root/polygon-edge-datadir/libp2p/libp2p.key
              subPath: libp2p.key
            - name: validator-config
              mountPath: /root/polygon-edge-datadir/genesis.json
              subPath: genesis.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: validator-config
          configMap:
            name: {{ include "polygon-edge.fullname" . }}-validator-config
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim  }}
        - name: polygon-edge-datadir
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        - name: polygon-edge-datadir
          hostPath:
            path: {{ .Values.persistence.hostPath.path }}
            type: {{ .Values.persistence.hostPath.type }}
{{- else if not .Values.persistence.enabled }}
        - name: polygon-edge-datadir
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: polygon-edge-datadir
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "polygon-edge.storageClass" . }}
{{- end }}
