apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokt-http-db.fullname" . }}
  labels:
    {{- include "pokt-http-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "pokt-http-db.selectorLabels" . | nindent 4 }}
