# TMP values to develop blockchain-node chart
# Will be deleted later
# blockchain-node:
statefulset:
  - name: pokt
    # replicas: N # default 1
    persistence:
      size: 200Gi
      storageClassName: local-path
      dataMountPath: /home/app/.pocket
      dataSnapshotURL: https://snapshot.nodes.pokt.network/latest.tar.gz
      # ebsSnapshot: #TODO
    initContainers: []
    containers:
      - name: pocket-core
        image:
          repository: poktnetwork/pocket
          tag: "RC-0.8.3"
        env:
          - name: DATA_TEST
            value: "test_data"
        workingDir: /data
        command: "pocket start \
          --datadir=/home/app/.pocket \
          --mainnet \
          --keybase=false"
        ports:
          - name: tendermint
            type: ClusterIP
            port: 26657
            protocol: TCP
          - name: rpc
            type: ClusterIP
            port: 8081
            protocol: TCP
            ingressNginx:
              host: pokt-seed10.nodes.pokt.network
          - name: tendermintpeers
            type: ClusterIP
            port: 26656
            protocol: TCP
          - name: monitoring
            type: ClusterIP
            port: 26660
            protocol: TCP
        mountSecrets:
          - name: seed10-keys        #  TODO: Will be created with external-secrets from HashiVaul                        
            mountPath: /secrets     # Depends from is it possible to adjust the path in the config file           
        mountConfigMaps:
          - name: pocket-core-config-json   #  TODO: iterate through all available keys in the CM and create mounts for each of them      
            mountPath: /home/app/.pocket/config
        resources:
          limits:
            cpu: 8
            memory: 15Gi
          requests:
            cpu: 4
            memory: 12Gi
        healthProbes:
          env:
            SIDECAR_CHAIN_ID: 0001
            HEIGHT_CHECK_STRATEGY: pocket
            REMOTE_RPC_ENDPOINTS: "https://SOME_PUBLIC_RPC"            
            STARTUP_PROBE_STRATEGY: localRpcAvailable
            READINESS_PROBE_STRATEGY: localVsRemote
            LIVENESS_PROBE_STRATEGY: heightNotClimbing
            LOCAL_RPC_ENDPOINT: "http://localhost:8081"
          # # Folowing is only for readyness
          # initialDelaySeconds: 120 # defaults
          # periodSeconds: 30        # defaults
          # timeoutSeconds: 1        # defaults
          # successThreshold: 1      # defaults
          # failureThreshold: 3      # defaults

# Additional manifests to deploy as an array
additionalManifests:
  - kind: SecretStore
    apiVersion: external-secrets.io/v1beta1
    metadata:
      name: vault-backend
    spec:
      controller: ""
      provider:
        vault:
          auth:
            kubernetes:
              mountPath: k8s-tooling-us-east-1
              role: seeds
              serviceAccountRef:
                name: seed10
          namespace: admin/engineering/
          path: /devops/seed10
          server: https://hcp-vault-cluster-a-public-vault-72230702.bb94b393.z1.hashicorp.cloud:8200
          version: v1
      refreshInterval: 0
  - kind: ExternalSecret
    apiVersion: external-secrets.io/v1beta1
    metadata:
      name: seed10-keys
    spec:
      secretStoreRef:
        name: secret-store-name
        kind: SecretStore  # or ClusterSecretStore
      refreshInterval: "1h"
      target:
        name: seed10-keys
        template:
          type: kubernetes.io/dockerconfigjson # or TLS...
          metadata:
            annotations: {}
            labels: {}
          data:
            config.yml: |
              endpoints:
              - https://{{`{{ .data.user }}`}}:{{`{{ .data.password }}`}}@api.exmaple.com
      data:
        - secretKey: secret-key-to-be-managed
          remoteRef:
            key: provider-key
            version: provider-key-version
            property: provider-key-property
            decodingStrategy: None # can be None, Base64, Base64URL or Auto

  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: pocket-core-config-json
    data:
      # ???                       
      # Can we specify a full path to the following files????                                  
      # This is needed to be able to mount the as k8s secrets - which can be mounted to        
      # "PrivValidatorKey": "priv_val_key.json",                                               
      # "NodeKey": "node_key.json",                                                            
      config.json: |
        {
            "tendermint_config": {
                "RootDir": "/home/app/.pocket",
                "ProxyApp": "tcp://127.0.0.1:26658",
                "Moniker": "pocket-core-seed10",
                "FastSyncMode": true,
                "DBBackend": "goleveldb",
                "LevelDBOptions": {
                    "block_cache_capacity": 83886,
                    "block_cache_evict_removed": false,
                    "block_size": 4096,
                    "disable_buffer_pool": true,
                    "open_files_cache_capacity": -1,
                    "write_buffer": 838860
                },
                "DBPath": "data",
                "LogLevel": "*:info, *:error",
                "LogFormat": "plain",
                "Genesis": "config/genesis.json",
                "PrivValidatorKey": "priv_val_key.json",                                  
                "PrivValidatorState": "priv_val_state.json",
                "PrivValidatorListenAddr": "",
                "NodeKey": "node_key.json",                                                
                "ABCI": "socket",
                "ProfListenAddress": "",
                "FilterPeers": false,
                "RPC": {
                    "RootDir": "/home/app/.pocket",
                    "ListenAddress": "tcp://0.0.0.0:26657",
                    "CORSAllowedOrigins": [],
                    "CORSAllowedMethods": [
                        "HEAD",
                        "GET",
                        "POST"
                    ],
                    "CORSAllowedHeaders": [
                        "Origin",
                        "Accept",
                        "Content-Type",
                        "X-Requested-With",
                        "X-Server-Time"
                    ],
                    "GRPCListenAddress": "",
                    "GRPCMaxOpenConnections": 2500,
                    "Unsafe": false,
                    "MaxOpenConnections": 2500,
                    "MaxSubscriptionClients": 100,
                    "MaxSubscriptionsPerClient": 5,
                    "TimeoutBroadcastTxCommit": 10000000000,
                    "MaxBodyBytes": 1000000,
                    "MaxHeaderBytes": 1048576,
                    "TLSCertFile": "",
                    "TLSKeyFile": ""
                },
                "P2P": {
                    "RootDir": "/home/app/.pocket",
                    "ListenAddress": "tcp://0.0.0.0:26656",
                    "ExternalAddress": "tcp://seed10.mainnet.pokt.network:29856",
                    "Seeds": "",
                    "PersistentPeers": "",
                    "UPNP": false,
                    "AddrBook": "config/addrbook.json",
                    "AddrBookStrict": false,
                    "MaxNumInboundPeers": 2000,
                    "MaxNumOutboundPeers": 2000,
                    "UnconditionalPeerIDs": "",
                    "PersistentPeersMaxDialPeriod": 0,
                    "FlushThrottleTimeout": 100000000,
                    "MaxPacketMsgPayloadSize": 1024,
                    "SendRate": 5120000,
                    "RecvRate": 5120000,
                    "PexReactor": true,
                    "SeedMode": true,
                    "PrivatePeerIDs": "",
                    "AllowDuplicateIP": true,
                    "HandshakeTimeout": 20000000000,
                    "DialTimeout": 3000000000,
                    "TestDialFail": false,
                    "TestFuzz": false,
                    "TestFuzzConfig": {
                        "Mode": 0,
                        "MaxDelay": 3000000000,
                        "ProbDropRW": 0.2,
                        "ProbDropConn": 0,
                        "ProbSleep": 0
                    }
                },
                "Mempool": {
                    "RootDir": "/home/app/.pocket",
                    "Recheck": true,
                    "Broadcast": true,
                    "WalPath": "",
                    "Size": 9000,
                    "MaxTxsBytes": 1073741824,
                    "CacheSize": 9000,
                    "MaxTxBytes": 1048576
                },
                "FastSync": {
                    "Version": "v1"
                },
                "Consensus": {
                    "RootDir": "/home/app/.pocket",
                    "WalPath": "data/cs.wal/wal",
                    "TimeoutPropose": 120000000000,
                    "TimeoutProposeDelta": 10000000000,
                    "TimeoutPrevote": 60000000000,
                    "TimeoutPrevoteDelta": 10000000000,
                    "TimeoutPrecommit": 60000000000,
                    "TimeoutPrecommitDelta": 10000000000,
                    "TimeoutCommit": 780000000000,
                    "SkipTimeoutCommit": false,
                    "CreateEmptyBlocks": true,
                    "CreateEmptyBlocksInterval": 900000000000,
                    "PeerGossipSleepDuration": 30000000000,
                    "PeerQueryMaj23SleepDuration": 20000000000
                },
                "TxIndex": {
                    "Indexer": "kv",
                    "IndexKeys": "tx.hash,tx.height,message.sender,transfer.recipient",
                    "IndexAllKeys": false
                },
                "Instrumentation": {
                    "Prometheus": true,
                    "PrometheusListenAddr": ":26660",
                    "MaxOpenConnections": 3,
                    "Namespace": "tendermint"
                }
            },
            "pocket_config": {
                "data_dir": "/home/app/.pocket",
                "genesis_file": "genesis.json",
                "chains_name": "chains.json",
                "session_db_name": "session",
                "evidence_db_name": "pocket_evidence",
                "tendermint_uri": "tcp://localhost:26657",
                "keybase_name": "pocket-keybase",
                "rpc_port": "8081",
                "client_block_sync_allowance": 10,
                "max_evidence_cache_entries": 500,
                "max_session_cache_entries": 500,
                "json_sort_relay_responses": true,
                "remote_cli_url": "http://localhost:8081",
                "user_agent": "",
                "validator_cache_size": 100,
                "application_cache_size": 100,
                "rpc_timeout": 10000,
                "pocket_prometheus_port": "8083",
                "prometheus_max_open_files": 3,
                "max_claim_age_for_proof_retry": 32,
                "proof_prevalidation": false,
                "ctx_cache_size": 20,
                "abci_logging": false,
                "show_relay_errors": true
            }
        }

global:
  serviceAccount:
    name: "pokt"
  securityContext:
    fsGroup: 1001
    runAsUser: 1005
    runAsGroup: 1001
    fsGroupChangePolicy: "OnRootMismatch"
