{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
type: Opaque
stringData:
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.clientSecret }}
  SENTRY_TOKEN: {{ .Values.auth.sentryToken }}
  GITHUB_TOKEN: {{ .Values.auth.githubToken }}
  PAGERDUTY_TOKEN: {{ .Values.auth.pagerdutyToken }}
{{- end }}
