{{- if .Values.externalSecrets.enabled -}}
---
kind: SecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: {{ include "backstage.fullname" . }}
spec:
  controller: {{ .Values.externalSecrets.controller }}
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.authMountPath }}
          role: {{ .Values.externalSecrets.role }}
          serviceAccountRef:
            name: {{ include "backstage.serviceAccountName" . }}
      namespace: {{ .Values.externalSecrets.namespace }}
      path: {{ .Values.externalSecrets.secretStoretPath }}
      server: {{ .Values.externalSecrets.vaultServer }}
      version: {{ .Values.externalSecrets.version }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "backstage.fullname" . }}
spec:
  refreshInterval: "20s"
  secretStoreRef:
    name: {{ include "backstage.fullname" . }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.targetName }}
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
  data:
    - secretKey: {{ .Values.externalSecrets.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: {{ .Values.externalSecrets.secretKey }}
{{- end }}
