---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum.fullname" . }}
  labels:
    {{- include "ethereum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: discovery-tcp
      port: 30303
      protocol: TCP
    - name: discovery-udp
      port: 30303
      protocol: UDP
    - name: rpc
      port: 8545
      protocol: TCP
    - name: ws
      port: 8546
      protocol: TCP
  selector:
    {{- include "ethereum.selectorLabels" . | nindent 4 }}
