apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokt-portal.fullname" . }}
  labels:
    {{- include "pokt-portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pokt-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pokt-portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pokt-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.middleware.enabled }}
        - name: middleware
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.middleware.image.repository }}:{{ .Values.middleware.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.middleware.service.port }}
              protocol: TCP
          {{- if .Values.middleware.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.middleware.livenessProbe.path | default "/healthz" }}
              port: http
            initialDelaySeconds: {{ .Values.middleware.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.middleware.livenessProbe.periodSeconds  | default 10 }}
            timeoutSeconds: {{ .Values.middleware.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.middleware.livenessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.middleware.livenessProbe.successThreshold | default 1}}
          {{- end }}
          {{- if .Values.middleware.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.middleware.readinessProbe.path | default "/healthz" }}
              port: http
            initialDelaySeconds: {{ .Values.middleware.readinessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.middleware.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.middleware.readinessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.middleware.readinessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.middleware.readinessProbe.successThreshold | default 1 }}
          {{- end }}
          volumeMounts:
          - mountPath: /config
            name: config
          env:
            - name: CONFIG_FILE
              value: /config/config.json
            - name: BACKEND_URL
              value: "http://localhost:{{ .Values.service.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- end }}
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "start"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
          {{- include "helpers.list-env-variables" . | indent 12 }}
          {{- if not .Values.externalSecrets.enabled }}
          {{- include "helpers.secret-env-variables" . | indent 12 }}
          {{- end }}
          {{- if .Values.externalSecrets.enabled }}
          envFrom:
          - secretRef:
              name: {{ include "pokt-portal.fullname" . }}-es
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.middleware.enabled }}
        - name: config
          configMap:
            name: {{ include "pokt-portal.fullname" . }}-config
        {{- end }}
