podAnnotations:
  reloader.stakater.com/auto: "true"
  
walletPassword: 
  password.txt: |-
    ilikeapples

network: "regtest"

configurationFile:
  lnd.conf: |-
    [Application Options]
    debuglevel=debug
    ; datadir=/data
    restlisten=0.0.0.0:8080
    rpclisten=0.0.0.0:10009
    listen=0.0.0.0:9735
    alias=LND Regtest
    wallet-unlock-password-file=/secure/password.txt

    [Bitcoin]
    bitcoin.node=bitcoind
    bitcoin.regtest=1
    bitcoin.active=1

    [bitcoind]
    bitcoind.rpchost=pvt-bitcoind-regtest:18443
    bitcoind.rpcuser=rpcuser
    bitcoind.rpcpass=rpcpassword
    bitcoind.zmqpubrawblock=tcp://pvt-bitcoind-regtest:28332
    bitcoind.zmqpubrawtx=tcp://pvt-bitcoind-regtest:28333
    
    [db]
    db.backend=postgres
    
    [postgres]
    db.postgres.dsn=postgres://<dbuser>:<dbpass>@dbsvc.default:5432/regtest

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "28800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "28800"

  hosts:
    - host: regtest.mynode.com
      path: "/"
      servicePort: 80
  tls:
    - secretName: lnd-regtest-cert
      hosts:
        - regtest.mynode.com