apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokt-portal-workers.fullname" . }}
  labels:
    {{- include "pokt-portal-workers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "pokt-portal-workers.selectorLabels" . | nindent 4 }}
