---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}-p2p
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
  selector:
    {{- include "lnd.selectorLabels" . | nindent 4 }}