apiVersion: v1
name: gcp-iam-externalsecrets
version: 0.3.0
description: A Helm chart to create a service account in your desired project, and grant it a specific role.
maintainers:
  - name: Grove Infra team