apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pokt-relay-meter.fullname" . }}-collector
  labels:
    app: {{ template "pokt-relay-meter.fullname" . }}
    chart: {{ template "pokt-relay-meter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.collector.configurationFile | indent 2 }}
