iapiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokt-relay-meter.fullname" . }}
  labels:
    {{- include "pokt-relay-meter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pokt-relay-meter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pokt-relay-meter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pokt-relay-meter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-collector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
          {{- if .Values.collector.configurationFile }}
          volumeMounts:
            - name: config-collector
              mountPath: /config
          {{- end }}
        - name: {{ .Chart.Name }}-apiserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.apiserver.image.repository }}:{{ .Values.apiserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          {{- if .Values.apiserver.configurationFile }}
          volumeMounts:
            - name: config-apiserver
              mountPath: /config
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configurationFile }}
      volumes:
        - name: config-collector
          configMap:
            name: {{ include "pokt-relay-meter.fullname" . }}-collector
            items:
            - key: .env
              path: .env
        - name: config-apiserver
          configMap:
            name: {{ include "pokt-relay-meter.fullname" . }}-apiserver
            items:
            - key: .env
              path: .env         
      {{- end }}
