{{- if .Values.collector.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-collector-vars
  labels:
    app: {{ template "pokt-relay-meter.fullname" . }}
    chart: {{ template "pokt-relay-meter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $val := .Values.collector.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end }}
