---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.1.0
    chart: ingress-nginx
    helm:
      parameters:
      - name: "controller.service.externalTrafficPolicy"
        value: "Local"
      - name: "controller.autoscaling.enabled"
        value: "true"
      - name: "controller.service.ipFamilies"
        value: "{IPv6}"
      valueFiles:
        - values.yaml
  project: utils
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true