# Default values for polygon-edge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

polygonEdge:
  # If you are unsure how to setup this information refer to https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-on-the-cloud
  genesisFile: |-
    {
      "name": "polygon-edge",
      "genesis": {
          "nonce": "0x0000000000000000",
          "timestamp": "0x0",
          "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000d8d5948ec1aa5385d1952400ffb519f958a749c45e3f1080c0",
          "gasLimit": "0x500000",
          "difficulty": "0x1",
          "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "coinbase": "0x0000000000000000000000000000000000000000",
          "alloc": {},
          "number": "0x0",
          "gasUsed": "0x70000",
          "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
      },
      "params": {
          "forks": {
              "homestead": 0,
              "byzantium": 0,
              "constantinople": 0,
              "petersburg": 0,
              "istanbul": 0,
              "EIP150": 0,
              "EIP158": 0,
              "EIP155": 0
          },
          "chainID": 100,
          "engine": {
              "ibft": {
                  "epochSize": 100000,
                  "type": "PoA"
              }
          },
          "blockGasTarget": 0
      },
      "bootnodes": [
          "/ip4/127.0.0.1/tcp/1478/p2p/16Uiu2HAmQ1U8TAP62nc91nvZKWnrpzyniV23wu8NGR93bYJJHmYA"
      ]
    }
  validator: 
    consensusValidatorKey: dfe83f0d105a42e7be598c7736e5050ec184ae0b260471bec919b250f4dccaef
    libp2pKey: 0802122052f650cadde3fff57c4cada89100bb83e59c8aac928ab8de60252b8f9a8091e8
  # Extra/un-managed arguments
  extraArgs: []

image:
  repository: 0xpolygon/polygon-edge
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

jsonrpc:
  port: 8545
  service:
    type: ClusterIP
    port: 8545
  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hostname: chart-example.local
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific
    # tls: [ ]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

p2p:
  port: 1478
  service:
    type: ClusterIP
    port: 1478
  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hostname: chart-example.local
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific
    # tls: [ ]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 1Gi

  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
  ##
  # existingClaim:
  ## An existing directory in the node
  ## If defined, host directory must be created manually before volume will be bound
  ## See https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
  ##
  hostPath:
    path: /run/desktop/mnt/host/wsl/polygon-edge-datadir
    type: DirectoryOrCreate

nodeSelector: {}

tolerations: []

affinity: {}