{{- range $ndpl, $dpl := $.Values.deployments }}
{{- range $kcntnr, $cntnr := $dpl.containers }}
{{- range $kprt, $prt := $cntnr.ports }}

{{- if $prt.ingress }}
{{- if or $prt.ingress.enabled (not (has $prt.ingress .enabled))}}{{/* # If enabled==true or not given*/}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "universal-helm.fullname" $ }}-{{$ndpl}}-{{ $prt.name }}
  labels:
    {{- include "universal-helm.labels" $ | nindent 4 }}
  {{- with $prt.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default "nginx" $prt.ingress.className }}
  {{- if $prt.ingress.tls }}
  tls:
    {{- range $prt.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $prt.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "universal-helm.fullname" $ }}-{{$ndpl}}-{{ $prt.name }}
                port:
                  number: {{ $prt.port }}
          {{- end }}
    {{- end }}

{{- end -}}{{- end -}}

{{- end -}}
{{- end -}}
{{- end -}}
