apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPort }}
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
    {{- if .Values.service.zmqPortBlk }}
    - name: zmq-blocks
      port: {{ .Values.service.zmqPortBlk }}
      targetPort: {{ .Values.service.zmqPortBlk }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.zmqPortTx }}
    - name: zmq-txs
      port: {{ .Values.service.zmqPortTx }}
      targetPort: {{ .Values.service.zmqPortTx }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}
