{{- range $kstfs, $sts := .Values.statefulset }}
{{- range $kcntnr, $cntnr := $sts.containers }}
{{- range $kprt, $prt := $cntnr.ports }}

{{- if $prt.GCPHTTPSLoadBalancer }}
# https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#create_service
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name}}
spec:
  {{- if $prt.GCPHTTPSLoadBalancer.CloudArmorPolicyName }}
  securityPolicy:
    name: {{ $prt.GCPHTTPSLoadBalancer.CloudArmorPolicyName }}
  {{- end }}
  healthCheck:
    type: HTTP
    requestPath: {{ quote $prt.GCPHTTPSLoadBalancer.healthCheck.requestPath }}
    port: {{ $prt.port }}

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name }}
spec:
  domains:
  {{- with $prt.GCPHTTPSLoadBalancer.domains }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name }}
  labels:
    {{- include "blockchain-node.labels" $ | nindent 4 }}
  annotations:
  {{- with $prt.GCPHTTPSLoadBalancer.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name }}
    kubernetes.io/ingress.allow-http: "false"
spec:
  defaultBackend:
    service:
      name: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name}}
      port:
        number: {{ $prt.port }}
  rules:
  - host:  {{ index $prt.GCPHTTPSLoadBalancer.domains 0 }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name}}
            port:
              number: {{ $prt.port }}
        path: /*
        pathType: ImplementationSpecific
{{- end -}}

{{- end -}}
{{- end -}}
{{- end -}}

