{{- range $kstfs, $sts := .Values.statefulset }}
{{- range $kcntnr, $cntnr := $sts.containers }}
{{- range $kprt, $prt := $cntnr.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain-node.fullname" $ }}-{{ $prt.name }}
  labels:
    {{- include "blockchain-node.labels" $ | nindent 4 }}
spec:
  selector:
    statefulsetname: {{ $sts.name }}
  type: {{ $prt.type }}
  ports:
    - port: {{ $prt.port }}
      targetPort: {{ $prt.port }}
      protocol: {{ $prt.protocol }}
      name: {{ $prt.name }}

{{- end -}}
{{- end -}}
{{- end -}}
