{{- range $kstfs, $sts := .Values.statefulset }}
{{- range $kcntnr, $cntnr := $sts.containers }}

{{- if $cntnr.healthProbes }}{{- if $cntnr.healthProbes.portToMonitor }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain-node.fullname" $ }}-rdnsprb{{ $cntnr.healthProbes.portToMonitor }}
  labels:
    {{- include "blockchain-node.labels" $ | nindent 4 }}
spec:
  selector:
    statefulsetname: {{ $sts.name }}
  ports:
    - port: 9090
      targetPort: 9090
      name: readiness

---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "blockchain-node.fullname" $ }}-rdnsprb{{ $cntnr.healthProbes.portToMonitor }}
spec:
  endpoints:
  - interval: 60s
    port: readiness
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "blockchain-node.labels" $ | nindent 6 }}

{{- end }}{{- end }}

{{- end -}}
{{- end -}}
