{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "portal-middleware.fullname" . }}
  labels:
    {{- include "portal-middleware.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "portal-middleware.fullname" . }}
  {{- if .Values.autoscaling.policies.enabled }}
  {{- include "portal-middleware.autoscaling-behavior" . | nindent 2 }}
  {{- end }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
      type: Resource
    {{- end }}
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
      type: Resource
    {{- end }}
{{- end }}
